// cnpg_bench -- headless dsp/-only benchmark (Task P1.10, docs/plan.md section 4.7 and Task
// P1.10 entry). Links cnpg_dsp ONLY -- zero JUCE, zero Catch2 -- so this target builds and runs
// on the ubuntu dsp-only CI job exactly like cnpg_dsp/cnpg_tests do (docs/plan.md section 1.5's
// naming registry). This is not a test: it is a report generator, and CI never gates on its
// numbers (docs/plan.md section 4.7 "Why CI never gates on performance"; the ci.yml `windows` job
// already runs it with `continue-on-error: true`).
//
// -----------------------------------------------------------------------------------------------
// What it does.
// -----------------------------------------------------------------------------------------------
//
// Assembles the exact hard-wired P1 chain plugin/src/PluginProcessor.cpp wires, at the plugin's
// own shipped defaults (plugin/src/Parameters.cpp -- the one place a dsp/ param struct's own
// default differs from what ships is TriodeStageParams::outputTrimDb, which the plugin sets to
// cnpg::dsp::kUnityGainOutputTrimDb):
//
//   StringNetwork -> PickupTap -> Oversampler(TriodeStage, bypassable) -> CabFilter (bypassable)
//                 -> OutputGain -> SoftClipLimiter
//
// The assembly itself lives in tests/support/P1Chain.h (cnpg::test::P1Chain /
// makeDefaultP1ChainParams) rather than here: Task P1.11 added cnpg_render, a second dsp/-only
// executable that must drive the identical chain for the corpus listening pass, and two
// hand-maintained copies of a six-module chain plus a six-call setParams cascade is exactly the
// thing that silently diverges by one parameter. See that header's file-level comment for the full
// rationale; everything this file's comments say about the chain's shape and its per-block cascade
// is still true, it is simply implemented one file over.
//
// cnpg_bench then drives it with a fixed, deterministic note stream (NoteStreamGenerator below) standing in
// for the real MIDI corpus -- the corpus itself (tests/corpus/) does not exist until Task P1.11,
// so "corpus-derived" here means "the same dense, arpeggiated, multi-string playing character the
// corpus phrases have", generated by pure integer/fixed-point arithmetic rather than by drawing
// from any RNG or the wall clock. That is what makes two runs of the same binary against the same
// CLI comparable sample-for-sample, not merely close in their timing summary.
//
// Every block is timed as a whole with a steady high-resolution clock, under the same
// ScopedFtzDazGuard RAII the plugin's processBlock() engages, matching the convention
// tests/dsp/DenormalTests.cpp already established for per-block timing in this repo. "As a whole"
// is load-bearing: PluginProcessor::renderChunk() unconditionally re-applies a freshly-read
// parameter snapshot to all six of StringNetwork/PickupTap/TriodeStage/CabFilter/OutputGain/
// SoftClipLimiter via setParams() BEFORE every process() call, every block, regardless of whether
// any value actually changed (docs/plan.md Task P1.1's once-per-block-snapshot design reads the
// APVTS atomics unconditionally) -- so that cascade is a real, unavoidable per-block cost in
// production and P1Chain::processBlock() reproduces it exactly, inside the timed region below,
// rather than applying params once outside the loop the way an early draft of this file did. Some
// of those six calls are cheap (CabFilter's is a single bool store) but several are not:
// PickupTap::setParams() recomputes a biquad's coefficients via sin()/cos() every call, and
// PickupTap/TriodeStage/OutputGain/SoftClipLimiter each convert a dB parameter through
// std::pow(10, x/20); StringNetwork::setParams() loops all kMaxStrings (8) rail slots --
// regardless of how many strings are actually active -- recomputing each one's target frequency
// via std::exp2() (dsp/src/StringNetwork.cpp's midiNoteToHz()). Excluding this cascade from the
// timed region would structurally UNDER-report every number below, and would make it impossible
// for p99/max to ever show the "event bursts, smoother retargeting" spike class docs/plan.md
// section 4.7 names as the reason those two columns are reported at all -- every block would cost
// exactly the same regardless of what happened in it.
//
// The parameter values themselves are constant across the whole render (cnpg_bench has no
// automation lane -- that is cnpg_render's job, driven by a corpus sidecar; the values here come
// straight from cnpg::test::makeDefaultP1ChainParams()) -- only the six setParams() CALLS repeat every
// block, exactly mirroring "every block, changed or not" rather than modelling automation cnpg_bench
// does not yet generate. Re-applying an unchanged target is provably a per-block no-op for the
// rendered SAMPLES (every setParams() implementation in dsp/ only recomputes a target a smoother
// then ramps toward -- ramping toward a target you are already sitting on moves nothing), which is
// why `audioHash` (see below) does not depend on whether this cascade runs; it is exclusively a
// per-block CPU cost, and that cost is exactly what this tool exists to measure.
//
// The first second of (block) time is excluded from the reported statistics as a warmup window --
// letting caches, the branch predictor and (on a laptop) any DVFS ramp settle before the numbers
// that get written into docs/bench/p1-baseline.md are sampled -- but every block, warmup included,
// is still rendered (setParams cascade and all) and still feeds the deterministic note-stream
// timeline, so excluding it from the stats never perturbs what gets played.
//
// -----------------------------------------------------------------------------------------------
// CLI (locked; P2.1 extended the --config table only -- see kNamedConfigs below).
// -----------------------------------------------------------------------------------------------
//
//   cnpg_bench [--config <name> | --strings N] --samplerate R --blocksize B --oversample F --seconds S
//
// --config and --strings are mutually exclusive. Task P2.1 filled in the two named configurations
// docs/plan.md asks for -- p2_default6 (6 strings) and p2_max8 (8) -- and that table IS the whole
// of its edit to this file's CLI surface: the parser and the validation are untouched, exactly as
// P1.10 predicted. A named config sets the string count and nothing else, so the remaining flags
// stay live on top of it. Every flag has a default, so `cnpg_bench` with no arguments at all
// (exactly what ci.yml's bench step runs) still executes the single-string configuration end to
// end and stays comparable with docs/bench/p1-baseline.md.
//
// -----------------------------------------------------------------------------------------------
// Output.
// -----------------------------------------------------------------------------------------------
//
// A human-readable report (median/p99/max block time, in both raw microseconds and as a percent
// of one core via blockTime/(blockSize/sampleRate), per docs/plan.md section 4.7's formula) to
// stdout, followed by one compact JSON line carrying the same numbers plus the full machine-spec
// schema docs/plan.md section 4.7 locks: "CPU model and core count, Windows power plan, compiler
// and version, build type and flags, git commit". CPU model is read from the registry on Windows
// (`HARDWARE\DESCRIPTION\System\CentralProcessor\0\ProcessorNameString`) and from /proc/cpuinfo's
// "model name" line elsewhere; core count is std::thread::hardware_concurrency() (logical, i.e.
// SMT/hyperthread-inclusive -- reported as "logicalCoreCount", not "cores", so the field name does
// not overclaim); the active power plan is read via a one-shot `powercfg /getactivescheme` on
// Windows (n/a elsewhere) -- see windowsPowerPlanGuid() below for why only the GUID is parsed out,
// not the (locale-dependent) friendly name; build type and flags are baked in at configure time
// (tests/bench/CMakeLists.txt) since neither is portably introspectable from inside a running
// process. Every one of these lookups runs once, outside the timed render loop, so none of them
// perturbs a block-time measurement; a failed lookup degrades to "unknown" (or "n/a" where the
// concept itself does not apply, e.g. Windows power plan on Linux) rather than aborting the run.

#include "support/P1Chain.h"

#include "cnpg/dsp/Common.h"
#include "cnpg/dsp/EventQueue.h"
#include "cnpg/dsp/Oversampler.h"
#include "cnpg/dsp/ScopedFtzDazGuard.h"

#include <algorithm>
#include <array>
#include <cerrno>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <string>
#include <thread>
#include <vector>

#if defined(_WIN32)
// NOMINMAX: without it, <windows.h> #defines min/max as function-like macros that silently
// swallow every std::min/std::max call in the rest of this file (a textual substitution, not a
// name lookup, so it is not scoped by namespace and breaks even fully-qualified std::min calls).
// WIN32_LEAN_AND_MEAN keeps the include itself cheap -- this file only needs RegGetValueA and
// _popen/_pclose, none of which live in the headers it excludes.
#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#if defined(_MSC_VER)
#pragma comment(lib, "advapi32.lib") // RegGetValueA, for the CPU-model registry read below
#endif
#else
#include <fstream> // /proc/cpuinfo parsing in cpuModel() below
#endif

#ifndef CNPG_BENCH_GIT_COMMIT
#define CNPG_BENCH_GIT_COMMIT "unknown" // safety net if a non-CMake build forgets to define this
#endif
#ifndef CNPG_BENCH_BUILD_TYPE
#define CNPG_BENCH_BUILD_TYPE "unknown" // safety net; see tests/bench/CMakeLists.txt
#endif
#ifndef CNPG_BENCH_BUILD_FLAGS
#define CNPG_BENCH_BUILD_FLAGS "unknown" // safety net; see tests/bench/CMakeLists.txt
#endif

#define CNPG_BENCH_STRINGIZE_IMPL(x) #x
#define CNPG_BENCH_STRINGIZE(x) CNPG_BENCH_STRINGIZE_IMPL(x)

using namespace cnpg::dsp;

namespace {

// The chain (cnpg::test::P1Chain, tests/support/P1Chain.h) and its per-block parameter set
// (cnpg::test::P1ChainParams, built by makeDefaultP1ChainParams()) are shared with cnpg_render --
// see that header for why they live there rather than here, and for the shipped-defaults note that
// used to sit at this spot. cnpg_bench builds the parameter set once in main() and holds it
// constant for the whole render: it has no automation lane, but see the file-level comment for why
// the six setParams() CALLS still repeat every block regardless.

// -------------------------------------------------------------------------------------------
// The deterministic "corpus-derived" note stream (see the file-level comment for why this is
// arithmetic, not a real corpus render, and not an RNG draw). Every active string is retriggered
// on its own fixed-period chromatic run, phase-staggered across strings so the workload stays
// dense (several strings overlapping and ringing at once, like real playing) without every
// retrigger landing in the same block -- which would make every block's cost look identical and
// defeat the point of reporting p99/max alongside the median.
// -------------------------------------------------------------------------------------------
class NoteStreamGenerator {
  public:
    NoteStreamGenerator(int numStrings, double sampleRate) : numStrings_(std::clamp(numStrings, 1, kMaxStrings)) {
        const long long interval = static_cast<long long>(kRetriggerIntervalSeconds * sampleRate + 0.5);
        intervalSamples_ = std::max<long long>(interval, 1);

        for (int s = 0; s < numStrings_; ++s) {
            const auto idx = static_cast<std::size_t>(s);
            const double phaseSeconds =
                kRetriggerIntervalSeconds * static_cast<double>(s) / static_cast<double>(numStrings_);
            nextRetriggerSample_[idx] = static_cast<long long>(phaseSeconds * sampleRate + 0.5);
            noteCycleIndex_[idx] = 0;
        }
    }

    // Pushes every event due inside [blockStartSample, blockStartSample + numSamples) into
    // `events`, in non-decreasing sampleOffset order (EventQueue::push's contract).
    void fillBlock(long long blockStartSample, int numSamples, BlockEventQueue& events) noexcept {
        const long long blockEndSample = blockStartSample + numSamples;

        due_.clear();
        for (int s = 0; s < numStrings_; ++s) {
            const auto idx = static_cast<std::size_t>(s);
            while (nextRetriggerSample_[idx] < blockEndSample) {
                due_.push_back(DueEvent{nextRetriggerSample_[idx], makeNoteEvent(s)});
                nextRetriggerSample_[idx] += intervalSamples_;
            }
        }

        std::sort(due_.begin(), due_.end(), [](const DueEvent& a, const DueEvent& b) { return a.sample < b.sample; });

        for (DueEvent& due : due_) {
            const long long relative = std::clamp<long long>(due.sample - blockStartSample, 0, numSamples - 1);
            due.event.sampleOffset = static_cast<std::int32_t>(relative);
            events.push(due.event);
        }
    }

  private:
    struct DueEvent {
        long long sample;
        NoteEvent event;
    };

    // ~4.5 retriggers/second/string: dense enough that a string is essentially always ringing
    // (representative of the corpus's "abuse" phrases, e.g. 04_palm_mute_chug's 16th notes at
    // 180 BPM is one retrigger every 0.083 s per string -- this is deliberately slower than that,
    // since cnpg_bench models steady-state playing density across up to 8 strings at once, not a
    // single-string worst case), while still resolving each pluck's transient separately.
    static constexpr double kRetriggerIntervalSeconds = 0.22;

    // A one-octave-ish pentatonic-flavoured run, deterministic and arbitrary: what matters for a
    // benchmark workload is that the pitch actually moves (exercising the per-sample f0 smoother
    // and, on a pitch change, the string re-initialization path StringNetwork.cpp's handleEvent()
    // takes), not any musical intent.
    static constexpr int kArpeggioSemitones[] = {0, 3, 5, 7, 10, 7, 5, 3};
    static constexpr std::size_t kArpeggioLength = sizeof(kArpeggioSemitones) / sizeof(kArpeggioSemitones[0]);

    static constexpr float kVelocityPattern[] = {1.0f, 0.72f, 0.88f, 0.6f, 0.94f, 0.8f};
    static constexpr std::size_t kVelocityPatternLength = sizeof(kVelocityPattern) / sizeof(kVelocityPattern[0]);

    // Standard 8-string guitar tuning, low to high (F#1 B1 E2 A2 D3 G3 B3 E4); the top six entries
    // are the standard 6-string tuning tests/dsp/DenormalTests.cpp's kChordNotes already uses.
    static constexpr int kOpenStringMidiNote[kMaxStrings] = {30, 35, 40, 45, 50, 55, 59, 64};

    int openStringNote(int stringIdx) const noexcept {
        const int baseIndex = kMaxStrings - numStrings_; // use the top numStrings_ strings
        return kOpenStringMidiNote[static_cast<std::size_t>(baseIndex + stringIdx)];
    }

    NoteEvent makeNoteEvent(int stringIdx) noexcept {
        const auto idx = static_cast<std::size_t>(stringIdx);

        NoteEvent event{};
        event.type = NoteEventType::NoteOn;
        event.sampleOffset = 0; // overwritten by fillBlock() once the block-relative offset is known
        event.stringIndex = static_cast<std::uint8_t>(stringIdx);
        event.channel = 0;

        const int rawNote = openStringNote(stringIdx) + kArpeggioSemitones[noteCycleIndex_[idx] % kArpeggioLength];
        event.midiNote = static_cast<std::uint8_t>(std::clamp(rawNote, kMinMidiNote, kMaxMidiNote));
        event.velocity = kVelocityPattern[(noteCycleIndex_[idx] + idx) % kVelocityPatternLength];
        // kUnspecifiedNoteParam: exactly what NoteAllocator emits for a plain MIDI note-on
        // (NoteAllocator.h), so the exciter resolves position/hardness against its own defaults --
        // i.e. cnpg_bench's events are shaped the way the real plugin's events are shaped.
        event.pluckPosition = kUnspecifiedNoteParam;
        event.hardness = kUnspecifiedNoteParam;

        ++noteCycleIndex_[idx];
        return event;
    }

    int numStrings_;
    long long intervalSamples_ = 1;
    std::array<long long, kMaxStrings> nextRetriggerSample_{};
    std::array<std::size_t, kMaxStrings> noteCycleIndex_{};
    std::vector<DueEvent> due_; // fillBlock() scratch; grows once, reused every call
};

// -------------------------------------------------------------------------------------------
// CLI
// -------------------------------------------------------------------------------------------

struct BenchArgs {
    int strings = 1;
    double sampleRate = 48000.0;
    int blockSize = 128;
    int oversample = Oversampler::kDefaultFactor;
    double seconds = 60.0;
    std::string configName;
};

void printNamedConfigs(std::FILE* stream);

void printUsage(std::FILE* stream) {
    std::fprintf(stream,
                 "usage: cnpg_bench [--config <name> | --strings N] --samplerate R --blocksize B "
                 "--oversample F --seconds S\n"
                 "  --config <name>  named bench configuration (sets the string count; see below)\n"
                 "  --strings N      active string count, 1..%d (default 1)\n"
                 "  --samplerate R   sample rate in Hz (default 48000)\n"
                 "  --blocksize B    block size in samples (default 128)\n"
                 "  --oversample F   oversampling factor, snapped to {2,4,8} (default %d)\n"
                 "  --seconds S      render length in seconds (default 60)\n",
                 kMaxStrings, Oversampler::kDefaultFactor);
    printNamedConfigs(stream);
}

bool parseDouble(const char* text, double& out) noexcept {
    char* end = nullptr;
    errno = 0;
    const double value = std::strtod(text, &end);
    if (end == text || *end != '\0' || errno == ERANGE || !std::isfinite(value))
        return false;
    out = value;
    return true;
}

bool parseInt(const char* text, int& out) noexcept {
    char* end = nullptr;
    errno = 0;
    const long value = std::strtol(text, &end, 10);
    if (end == text || *end != '\0' || errno == ERANGE || value < std::numeric_limits<int>::min() ||
        value > std::numeric_limits<int>::max())
        return false;
    out = static_cast<int>(value);
    return true;
}

// Named --config resolution. Task P1.10 left this table empty and predicted that P2.1 would be the
// only place that ever needs to touch this function; that held exactly -- the two rows below are
// the whole of P2.1's edit to this file's CLI surface, and the parser, the validation and the error
// text above and below are untouched.
//
// A named config fixes ONLY the string count. Everything else about both configurations -- the full
// P1 monitoring chain, the shipped parameter defaults, 2x oversampling -- is what cnpg_bench
// already runs, so the rows do not restate it and cannot drift from it. The remaining flags stay
// live on top of a --config, which is what makes `--config p2_max8 --samplerate 96000` a question
// this tool can answer without a third named row.
struct NamedConfig {
    const char* name;
    int strings;
    const char* description;
};
constexpr NamedConfig kNamedConfigs[] = {
    {"p2_default6", 6, "the shipped default count: 6 strings through the full P1 monitoring chain"},
    {"p2_max8", 8, "the design maximum: 8 strings, same chain"},
};

bool resolveNamedConfig(const std::string& name, int& outStrings) noexcept {
    for (const NamedConfig& config : kNamedConfigs) {
        if (name == config.name) {
            outStrings = config.strings;
            return true;
        }
    }
    return false;
}

void printNamedConfigs(std::FILE* stream) {
    std::fprintf(stream, "named configurations:\n");
    for (const NamedConfig& config : kNamedConfigs)
        std::fprintf(stream, "  %-12s %d strings -- %s\n", config.name, config.strings, config.description);
}

bool parseArgs(int argc, char** argv, BenchArgs& args, bool& configGiven, bool& stringsGiven) {
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];

        const auto nextValue = [&](const char* flagName) -> const char* {
            if (i + 1 >= argc) {
                std::fprintf(stderr, "cnpg_bench: missing value for %s\n", flagName);
                return nullptr;
            }
            return argv[++i];
        };

        if (arg == "--config") {
            const char* value = nextValue("--config");
            if (value == nullptr)
                return false;
            args.configName = value;
            configGiven = true;
        } else if (arg == "--strings") {
            const char* value = nextValue("--strings");
            if (value == nullptr || !parseInt(value, args.strings)) {
                std::fprintf(stderr, "cnpg_bench: invalid --strings value\n");
                return false;
            }
            stringsGiven = true;
        } else if (arg == "--samplerate") {
            const char* value = nextValue("--samplerate");
            if (value == nullptr || !parseDouble(value, args.sampleRate)) {
                std::fprintf(stderr, "cnpg_bench: invalid --samplerate value\n");
                return false;
            }
        } else if (arg == "--blocksize") {
            const char* value = nextValue("--blocksize");
            if (value == nullptr || !parseInt(value, args.blockSize)) {
                std::fprintf(stderr, "cnpg_bench: invalid --blocksize value\n");
                return false;
            }
        } else if (arg == "--oversample") {
            const char* value = nextValue("--oversample");
            if (value == nullptr || !parseInt(value, args.oversample)) {
                std::fprintf(stderr, "cnpg_bench: invalid --oversample value\n");
                return false;
            }
        } else if (arg == "--seconds") {
            const char* value = nextValue("--seconds");
            if (value == nullptr || !parseDouble(value, args.seconds)) {
                std::fprintf(stderr, "cnpg_bench: invalid --seconds value\n");
                return false;
            }
        } else if (arg == "--help" || arg == "-h") {
            printUsage(stdout);
            std::exit(0);
        } else {
            std::fprintf(stderr, "cnpg_bench: unknown argument '%s'\n", arg.c_str());
            return false;
        }
    }
    return true;
}

// -------------------------------------------------------------------------------------------
// Stats
// -------------------------------------------------------------------------------------------

// Nearest-rank percentile over an already-sorted (ascending) vector. Not linear-interpolated:
// docs/plan.md section 4.7 only ever asks for "median, p99, and max", and the P1.8 ledger note
// (single-run figures get ~2 significant figures on a shared workstation) makes interpolation
// precision here moot -- nearest-rank also matches the simpler median() helper
// tests/dsp/DenormalTests.cpp already established for this repo's block-timing reports.
double percentileOfSorted(const std::vector<double>& sorted, double p) noexcept {
    if (sorted.empty())
        return 0.0;
    const auto rank = static_cast<std::size_t>(p * static_cast<double>(sorted.size() - 1) + 0.5);
    return sorted[std::min(rank, sorted.size() - 1)];
}

const char* compilerName() noexcept {
#if defined(_MSC_VER)
    return "MSVC " CNPG_BENCH_STRINGIZE(_MSC_VER);
#elif defined(__clang__)
    return "Clang " __clang_version__;
#elif defined(__GNUC__)
    return "GCC " CNPG_BENCH_STRINGIZE(__GNUC__) "." CNPG_BENCH_STRINGIZE(__GNUC_MINOR__);
#else
    return "unknown";
#endif
}

// -------------------------------------------------------------------------------------------
// Environment (docs/plan.md section 4.7's locked JSON schema: "CPU model and core count, Windows
// power plan, compiler and version, build type and flags, git commit"). Every lookup below runs
// exactly once, from main(), outside the timed render loop.
// -------------------------------------------------------------------------------------------

// Replaces '"', '\\' and any control character with '_' so a runtime-sourced string (the only
// untrusted-shape strings here: cpuModel() reads the registry / /proc/cpuinfo) can never produce
// invalid JSON when dropped into this file's hand-written printf format strings.
std::string sanitizeForJson(std::string s) {
    for (char& c : s) {
        if (c == '"' || c == '\\' || static_cast<unsigned char>(c) < 0x20)
            c = '_';
    }
    return s;
}

std::string cpuModel() {
#if defined(_WIN32)
    char buffer[256] = {};
    DWORD bufferSize = sizeof(buffer);
    const LONG result = RegGetValueA(HKEY_LOCAL_MACHINE, "HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0",
                                     "ProcessorNameString", RRF_RT_REG_SZ, nullptr, buffer, &bufferSize);
    if (result != ERROR_SUCCESS)
        return "unknown";
    std::string name(buffer);
    while (!name.empty() && (name.back() == ' ' || name.back() == '\0'))
        name.pop_back();
    return name.empty() ? "unknown" : sanitizeForJson(name);
#else
    std::ifstream cpuinfo("/proc/cpuinfo");
    if (!cpuinfo.is_open())
        return "unknown";
    std::string line;
    while (std::getline(cpuinfo, line)) {
        if (line.rfind("model name", 0) != 0)
            continue;
        const auto colon = line.find(':');
        if (colon == std::string::npos)
            break;
        std::string name = line.substr(colon + 1);
        const auto firstNonSpace = name.find_first_not_of(' ');
        return firstNonSpace == std::string::npos ? "unknown" : sanitizeForJson(name.substr(firstNonSpace));
    }
    return "unknown";
#endif
}

// std::thread::hardware_concurrency() reports LOGICAL processors (SMT/hyperthread siblings
// included), not physical cores -- named accordingly below rather than as "core count" so the
// field never overclaims what it actually measured.
unsigned int logicalCoreCount() noexcept { return std::thread::hardware_concurrency(); }

// Windows-only: the active power plan, read via a one-shot `powercfg /getactivescheme` spawn.
// Only the plan's GUID is extracted (not the friendly name after it in parentheses): powercfg's
// surrounding text is localized -- this dev machine's own output is Korean, e.g.
// "...GUID: e9a42b02-d5df-448d-aa00-03f14749eb61  (<localized plan name>)" -- but the GUID itself
// is not, so scanning for the fixed 8-4-4-4-12 hex shape anywhere in the output is the one locale-independent
// way to parse this reliably. The human-readable plan name still belongs in
// docs/bench/p1-baseline.md (recorded by hand, where it already is), not in this JSON line.
std::string windowsPowerPlanGuid() {
#if defined(_WIN32)
    std::FILE* pipe = _popen("powercfg /getactivescheme", "r");
    if (pipe == nullptr)
        return "unknown";

    std::string output;
    char buf[256];
    while (std::fgets(buf, sizeof(buf), pipe) != nullptr)
        output += buf;
    _pclose(pipe);

    const auto isHex = [](char c) noexcept {
        return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F');
    };
    for (std::size_t i = 0; i + 36 <= output.size(); ++i) {
        bool matches = true;
        for (int j = 0; j < 36 && matches; ++j) {
            const char c = output[i + static_cast<std::size_t>(j)];
            const bool wantDash = (j == 8 || j == 13 || j == 18 || j == 23);
            matches = wantDash ? (c == '-') : isHex(c);
        }
        if (matches)
            return output.substr(i, 36);
    }
    return "unknown";
#else
    return "n/a";
#endif
}

} // namespace

int main(int argc, char** argv) {
    BenchArgs args;
    bool configGiven = false;
    bool stringsGiven = false;

    if (!parseArgs(argc, argv, args, configGiven, stringsGiven)) {
        printUsage(stderr);
        return 1;
    }

    if (configGiven && stringsGiven) {
        std::fprintf(stderr, "cnpg_bench: specify either --config or --strings, not both\n");
        return 1;
    }

    if (configGiven) {
        int resolvedStrings = 0;
        if (!resolveNamedConfig(args.configName, resolvedStrings)) {
            std::fprintf(stderr, "cnpg_bench: unknown --config '%s'\n", args.configName.c_str());
            printNamedConfigs(stderr);
            return 1;
        }
        args.strings = resolvedStrings;
    }

    if (args.strings < 1 || args.strings > kMaxStrings) {
        std::fprintf(stderr, "cnpg_bench: --strings must be within 1..%d\n", kMaxStrings);
        return 1;
    }
    if (!(args.sampleRate > 0.0) || args.sampleRate > 500000.0) {
        std::fprintf(stderr, "cnpg_bench: --samplerate must be a positive, finite value\n");
        return 1;
    }
    if (args.blockSize < 1 || args.blockSize > 1000000) {
        std::fprintf(stderr, "cnpg_bench: --blocksize must be within 1..1000000\n");
        return 1;
    }
    if (args.oversample < 1 || args.oversample > kMaxOversampling) {
        std::fprintf(stderr, "cnpg_bench: --oversample must be within 1..%d (snapped to {2,4,8})\n", kMaxOversampling);
        return 1;
    }
    if (!(args.seconds > 0.0) || args.seconds > 100000.0) {
        std::fprintf(stderr, "cnpg_bench: --seconds must be a positive, finite value\n");
        return 1;
    }

    cnpg::test::P1Chain chain;
    chain.prepare(args.sampleRate, args.blockSize, args.strings, args.oversample);
    chain.reset();

    // Built once; re-applied to every module every block from inside the timed region (see the
    // file-level comment and cnpg::test::P1Chain::processBlock()).
    cnpg::test::P1ChainParams chainParams = cnpg::test::makeDefaultP1ChainParams();
    chainParams.numStrings = args.strings;

    NoteStreamGenerator generator(args.strings, args.sampleRate);

    const auto totalSamples = static_cast<long long>(args.seconds * args.sampleRate);
    constexpr double kWarmupSeconds = 1.0;
    const auto warmupSamplesRaw = static_cast<long long>(kWarmupSeconds * args.sampleRate);
    const long long warmupSamples = std::min(warmupSamplesRaw, totalSamples / 2);

    BlockEventQueue events;
    std::vector<double> blockMicros; // every measured block, in render order
    blockMicros.reserve(static_cast<std::size_t>(totalSamples / std::max(args.blockSize, 1) + 1));

    long long rendered = 0;
    long long nonFiniteSamples = 0;
    int warmupBlocks = 0;

    // FNV-1a over every rendered sample's raw bit pattern (untimed -- computed after `elapsed` is
    // captured, so it never pollutes a block-time measurement). This is the empirical determinism
    // check docs/plan.md section 4.7's "seeded/fixed... so runs are comparable" is asking for:
    // two runs with identical CLI arguments must print an identical audioHash, which is a much
    // stronger claim than "the note stream and the DSP chain contain no RNG or wall-clock read, so
    // it should be deterministic by construction" -- this is what actually checks that construction
    // held, on the real compiled binary, every time it runs.
    std::uint64_t audioHash = 14695981039346656037ull; // FNV-1a 64-bit offset basis
    constexpr std::uint64_t kFnvPrime = 1099511628211ull;

    while (rendered < totalSamples) {
        const auto numSamples = static_cast<int>(std::min<long long>(args.blockSize, totalSamples - rendered));

        events.clear();
        generator.fillBlock(rendered, numSamples, events);

        const auto start = std::chrono::steady_clock::now();
        {
            const ScopedFtzDazGuard ftzDazGuard; // exactly the guard the plugin's processBlock() engages
            chain.processBlock(chainParams, events, numSamples);
        }
        const auto elapsed = std::chrono::steady_clock::now() - start;
        const double micros =
            static_cast<double>(std::chrono::duration_cast<std::chrono::nanoseconds>(elapsed).count()) / 1000.0;

        blockMicros.push_back(micros);
        if (rendered < warmupSamples)
            ++warmupBlocks;

        for (int n = 0; n < numSamples; ++n) {
            const Sample sample = chain.mono[static_cast<std::size_t>(n)];
            nonFiniteSamples += std::isfinite(sample) ? 0 : 1;

            std::uint32_t bits = 0;
            std::memcpy(&bits, &sample, sizeof(bits));
            audioHash ^= bits;
            audioHash *= kFnvPrime;
        }

        rendered += numSamples;
    }

    // Clamp the warmup cut so at least one measured block always survives, even for a --seconds
    // value too short for a full kWarmupSeconds window (an edge case only a deliberately tiny
    // --seconds for smoke-testing the CLI would hit).
    const auto warmupCount = static_cast<std::size_t>(std::min(
        warmupBlocks, static_cast<int>(blockMicros.size()) - 1 < 0 ? 0 : static_cast<int>(blockMicros.size()) - 1));

    std::vector<double> stable(blockMicros.begin() + static_cast<std::vector<double>::difference_type>(warmupCount),
                               blockMicros.end());
    std::sort(stable.begin(), stable.end());

    const double medianMicros = percentileOfSorted(stable, 0.50);
    const double p99Micros = percentileOfSorted(stable, 0.99);
    const double maxMicros = stable.empty() ? 0.0 : stable.back();

    const double blockPeriodMicros = 1000000.0 * static_cast<double>(args.blockSize) / args.sampleRate;
    const auto toCpuPercent = [&](double micros) { return 100.0 * micros / blockPeriodMicros; };

    const int factor = chain.oversampler.factor();

    // Every lookup below runs once, here, outside the timed loop above.
    const std::string cpuModelStr = cpuModel();
    const unsigned int coreCount = logicalCoreCount();
    const std::string powerPlanGuid = windowsPowerPlanGuid();

    std::printf("cnpg_bench -- P1 monitoring chain, deterministic corpus-derived workload\n");
    std::printf("  strings=%d samplerate=%.0f blocksize=%d oversample=%d(requested %d) seconds=%.1f\n", args.strings,
                args.sampleRate, args.blockSize, factor, args.oversample, args.seconds);
    std::printf("  blocks total=%d measured=%d (warmup excluded=%d) nonFiniteSamples=%lld\n",
                static_cast<int>(blockMicros.size()), static_cast<int>(stable.size()), static_cast<int>(warmupCount),
                nonFiniteSamples);
    std::printf("  audioHash (FNV-1a/64 over every rendered sample; identical CLI args -> identical hash): "
                "%016llx\n",
                static_cast<unsigned long long>(audioHash));
    std::printf("  block period at this rate/blocksize: %.4f us (100%% of one core)\n", blockPeriodMicros);
    std::printf("  median block time: %10.3f us = %6.3f%% CPU\n", medianMicros, toCpuPercent(medianMicros));
    std::printf("  p99    block time: %10.3f us = %6.3f%% CPU\n", p99Micros, toCpuPercent(p99Micros));
    std::printf("  max    block time: %10.3f us = %6.3f%% CPU\n", maxMicros, toCpuPercent(maxMicros));
    std::printf("  environment: cpu=\"%s\" logicalCores=%u powerPlanGuid=%s compiler=\"%s\" buildType=%s "
                "gitCommit=%s\n",
                cpuModelStr.c_str(), coreCount, powerPlanGuid.c_str(), compilerName(), CNPG_BENCH_BUILD_TYPE,
                CNPG_BENCH_GIT_COMMIT);

    std::printf("{\"strings\":%d,\"sampleRate\":%.0f,\"blockSize\":%d,\"oversampleFactor\":%d,"
                "\"secondsRequested\":%.1f,\"blocksTotal\":%d,\"blocksMeasured\":%d,\"warmupBlocksExcluded\":%d,"
                "\"nonFiniteSamples\":%lld,\"audioHash\":\"%016llx\",\"medianBlockTimeUs\":%.3f,"
                "\"p99BlockTimeUs\":%.3f,\"maxBlockTimeUs\":%.3f,\"medianCpuPercent\":%.3f,\"p99CpuPercent\":%.3f,"
                "\"maxCpuPercent\":%.3f,\"cpuModel\":\"%s\",\"logicalCoreCount\":%u,\"powerPlanGuid\":\"%s\","
                "\"compiler\":\"%s\",\"buildType\":\"%s\",\"buildFlags\":\"%s\",\"gitCommit\":\"%s\"}\n",
                args.strings, args.sampleRate, args.blockSize, factor, args.seconds,
                static_cast<int>(blockMicros.size()), static_cast<int>(stable.size()), static_cast<int>(warmupCount),
                nonFiniteSamples, static_cast<unsigned long long>(audioHash), medianMicros, p99Micros, maxMicros,
                toCpuPercent(medianMicros), toCpuPercent(p99Micros), toCpuPercent(maxMicros), cpuModelStr.c_str(),
                coreCount, powerPlanGuid.c_str(), compilerName(), CNPG_BENCH_BUILD_TYPE, CNPG_BENCH_BUILD_FLAGS,
                CNPG_BENCH_GIT_COMMIT);

    return 0;
}
