// cnpg_bench -- headless dsp/-only benchmark (Task P1.10, docs/plan.md section 4.7 and Task
// P1.10 entry). Links cnpg_dsp ONLY -- zero JUCE, zero Catch2 -- so this target builds and runs
// on the ubuntu dsp-only CI job exactly like cnpg_dsp/cnpg_tests do (docs/plan.md section 1.5's
// naming registry). This is not a test: it is a report generator, and CI never gates on its
// numbers (docs/plan.md section 4.7 "Why CI never gates on performance"; the ci.yml `windows` job
// already runs it with `continue-on-error: true`).
//
// -----------------------------------------------------------------------------------------------
// What it does.
// -----------------------------------------------------------------------------------------------
//
// Assembles the exact hard-wired P1 chain plugin/src/PluginProcessor.cpp wires, at the plugin's
// own shipped defaults (plugin/src/Parameters.cpp -- the one place a dsp/ param struct's own
// default differs from what ships is TriodeStageParams::outputTrimDb, which the plugin sets to
// cnpg::dsp::kUnityGainOutputTrimDb; BenchChain::setDefaults() below matches that, exactly as
// tests/dsp/MonitoringChainTests.cpp's ChainHarness does):
//
//   StringNetwork -> PickupTap -> Oversampler(TriodeStage, bypassable) -> CabFilter (bypassable)
//                 -> OutputGain -> SoftClipLimiter
//
// then drives it with a fixed, deterministic note stream (NoteStreamGenerator below) standing in
// for the real MIDI corpus -- the corpus itself (tests/corpus/) does not exist until Task P1.11,
// so "corpus-derived" here means "the same dense, arpeggiated, multi-string playing character the
// corpus phrases have", generated by pure integer/fixed-point arithmetic rather than by drawing
// from any RNG or the wall clock. That is what makes two runs of the same binary against the same
// CLI comparable sample-for-sample, not merely close in their timing summary.
//
// Every process() call is timed individually with a steady high-resolution clock, under the same
// ScopedFtzDazGuard RAII the plugin's processBlock() engages, matching the convention
// tests/dsp/DenormalTests.cpp already established for per-block timing in this repo. The first
// second of (block) time is excluded from the reported statistics as a warmup window -- letting
// caches, the branch predictor and (on a laptop) any DVFS ramp settle before the numbers that get
// written into docs/bench/p1-baseline.md are sampled -- but every block, warmup included, is still
// rendered and still feeds the deterministic note-stream timeline, so excluding it from the stats
// never perturbs what gets played.
//
// -----------------------------------------------------------------------------------------------
// CLI (locked; P2.1 extends the --config table only -- see kNamedConfigs below).
// -----------------------------------------------------------------------------------------------
//
//   cnpg_bench [--config <name> | --strings N] --samplerate R --blocksize B --oversample F --seconds S
//
// --config and --strings are mutually exclusive. No named --config values exist yet (they arrive
// in Task P2.1 as p2_default6/p2_max8, docs/plan.md line 1146); resolveNamedConfig() below always
// reports "not found" through P1, so P2.1's whole edit to this file's CLI surface is filling in
// kNamedConfigs' table -- the parser, validation, and error text never change. Every flag
// has a default so `cnpg_bench` with no arguments at all (exactly what ci.yml's bench step runs)
// still executes the P1 single-string configuration end to end.
//
// -----------------------------------------------------------------------------------------------
// Output.
// -----------------------------------------------------------------------------------------------
//
// A human-readable report (median/p99/max block time, in both raw microseconds and as a percent
// of one core via blockTime/(blockSize/sampleRate), per docs/plan.md section 4.7's formula) to
// stdout, followed by one compact JSON line carrying the same numbers plus what this binary can
// portably self-report (compiler, optimization mode, git commit baked in at configure time -- see
// tests/bench/CMakeLists.txt) for docs/plan.md section 4.7's "every run emits JSON" intent. CPU
// model and Windows power plan are NOT self-reported here (no WinAPI dependency was worth adding
// to an otherwise OS-agnostic dsp/-only executable for two fields that a human has to read off the
// dev machine once per baseline anyway) -- they are recorded by hand in docs/bench/p1-baseline.md
// instead, exactly where docs/plan.md's own acceptance criterion asks for "dev-machine spec".

#include "cnpg/dsp/CabFilter.h"
#include "cnpg/dsp/Common.h"
#include "cnpg/dsp/EventQueue.h"
#include "cnpg/dsp/OutputGain.h"
#include "cnpg/dsp/Oversampler.h"
#include "cnpg/dsp/PickupTap.h"
#include "cnpg/dsp/ScopedFtzDazGuard.h"
#include "cnpg/dsp/SoftClipLimiter.h"
#include "cnpg/dsp/StringNetwork.h"
#include "cnpg/dsp/TriodeStage.h"

#include <algorithm>
#include <array>
#include <cerrno>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <string>
#include <vector>

#ifndef CNPG_BENCH_GIT_COMMIT
#define CNPG_BENCH_GIT_COMMIT "unknown" // safety net if a non-CMake build forgets to define this
#endif

#define CNPG_BENCH_STRINGIZE_IMPL(x) #x
#define CNPG_BENCH_STRINGIZE(x) CNPG_BENCH_STRINGIZE_IMPL(x)

using namespace cnpg::dsp;

namespace {

// -------------------------------------------------------------------------------------------
// The chain: StringNetwork -> PickupTap -> Oversampler(TriodeStage) -> CabFilter -> OutputGain
// -> SoftClipLimiter, assembled exactly as plugin/src/PluginProcessor.cpp and
// tests/dsp/MonitoringChainTests.cpp's ChainHarness assemble it. A separate copy rather than a
// shared header: cnpg_bench and cnpg_tests are different executables (cnpg_bench links cnpg_dsp
// only, per the naming registry), so there is no single target both could include this from
// without pulling Catch2 into cnpg_bench or cnpg_dsp into a place it does not belong.
// -------------------------------------------------------------------------------------------
struct BenchChain {
    StringNetwork<float> network;
    PickupTap pickup;
    Oversampler oversampler;
    TriodeStage triode;
    CabFilter cab;
    OutputGain outputGain;
    SoftClipLimiter limiter;

    std::vector<Sample> mono;

    void prepare(double sampleRate, int blockSize, int numStrings, int oversampleFactorRequested) {
        network.prepare(sampleRate, blockSize, FractionalDelayKind::Lagrange3);
        network.setNumStrings(numStrings);
        pickup.prepare(sampleRate, blockSize);
        oversampler.prepare(sampleRate, blockSize, oversampleFactorRequested);
        // The wrapped nonlinearity runs at factor * sampleRate on blocks of up to
        // maxBlockSize * factor samples (Oversampler.h's wiring note for P1.9).
        triode.prepare(sampleRate * oversampler.factor(), blockSize * oversampler.factor());
        cab.prepare(sampleRate, blockSize);
        outputGain.prepare(sampleRate, blockSize);
        limiter.prepare(sampleRate, blockSize);

        mono.assign(static_cast<std::size_t>(blockSize), 0.0f);
    }

    // The SHIPPED defaults -- see the file-level comment for why the triode's output trim is the
    // one field that is not simply <Module>Params{}.
    void setDefaults() {
        network.setParams(StringNetworkParams{});
        pickup.setParams(PickupTapParams{});

        TriodeStageParams triodeParams;
        triodeParams.outputTrimDb = kUnityGainOutputTrimDb;
        triode.setParams(triodeParams);

        cab.setParams(CabFilterParams{});
        outputGain.setParams(OutputGainParams{});
        limiter.setParams(SoftClipLimiterParams{});
    }

    void reset() noexcept {
        network.reset();
        pickup.reset();
        oversampler.reset();
        triode.reset();
        cab.reset();
        outputGain.reset();
        limiter.reset();
    }

    void processBlock(BlockEventQueue& events, int numSamples) noexcept {
        network.process(events, numSamples);
        pickup.process(network.tapBuffers(), mono.data(), numSamples);
        oversampler.processWrapped(
            mono.data(), mono.data(), numSamples,
            [this](Sample* buffer, int numUpsampled) noexcept { triode.process(buffer, buffer, numUpsampled); });
        cab.process(mono.data(), mono.data(), numSamples);
        outputGain.process(mono.data(), mono.data(), numSamples);
        limiter.process(mono.data(), mono.data(), numSamples);
    }
};

// -------------------------------------------------------------------------------------------
// The deterministic "corpus-derived" note stream (see the file-level comment for why this is
// arithmetic, not a real corpus render, and not an RNG draw). Every active string is retriggered
// on its own fixed-period chromatic run, phase-staggered across strings so the workload stays
// dense (several strings overlapping and ringing at once, like real playing) without every
// retrigger landing in the same block -- which would make every block's cost look identical and
// defeat the point of reporting p99/max alongside the median.
// -------------------------------------------------------------------------------------------
class NoteStreamGenerator {
  public:
    NoteStreamGenerator(int numStrings, double sampleRate) : numStrings_(std::clamp(numStrings, 1, kMaxStrings)) {
        const long long interval = static_cast<long long>(kRetriggerIntervalSeconds * sampleRate + 0.5);
        intervalSamples_ = std::max<long long>(interval, 1);

        for (int s = 0; s < numStrings_; ++s) {
            const auto idx = static_cast<std::size_t>(s);
            const double phaseSeconds =
                kRetriggerIntervalSeconds * static_cast<double>(s) / static_cast<double>(numStrings_);
            nextRetriggerSample_[idx] = static_cast<long long>(phaseSeconds * sampleRate + 0.5);
            noteCycleIndex_[idx] = 0;
        }
    }

    // Pushes every event due inside [blockStartSample, blockStartSample + numSamples) into
    // `events`, in non-decreasing sampleOffset order (EventQueue::push's contract).
    void fillBlock(long long blockStartSample, int numSamples, BlockEventQueue& events) noexcept {
        const long long blockEndSample = blockStartSample + numSamples;

        due_.clear();
        for (int s = 0; s < numStrings_; ++s) {
            const auto idx = static_cast<std::size_t>(s);
            while (nextRetriggerSample_[idx] < blockEndSample) {
                due_.push_back(DueEvent{nextRetriggerSample_[idx], makeNoteEvent(s)});
                nextRetriggerSample_[idx] += intervalSamples_;
            }
        }

        std::sort(due_.begin(), due_.end(), [](const DueEvent& a, const DueEvent& b) { return a.sample < b.sample; });

        for (DueEvent& due : due_) {
            const long long relative = std::clamp<long long>(due.sample - blockStartSample, 0, numSamples - 1);
            due.event.sampleOffset = static_cast<std::int32_t>(relative);
            events.push(due.event);
        }
    }

  private:
    struct DueEvent {
        long long sample;
        NoteEvent event;
    };

    // ~4.5 retriggers/second/string: dense enough that a string is essentially always ringing
    // (representative of the corpus's "abuse" phrases, e.g. 04_palm_mute_chug's 16th notes at
    // 180 BPM is one retrigger every 0.083 s per string -- this is deliberately slower than that,
    // since cnpg_bench models steady-state playing density across up to 8 strings at once, not a
    // single-string worst case), while still resolving each pluck's transient separately.
    static constexpr double kRetriggerIntervalSeconds = 0.22;

    // A one-octave-ish pentatonic-flavoured run, deterministic and arbitrary: what matters for a
    // benchmark workload is that the pitch actually moves (exercising the per-sample f0 smoother
    // and, on a pitch change, the string re-initialization path StringNetwork.cpp's handleEvent()
    // takes), not any musical intent.
    static constexpr int kArpeggioSemitones[] = {0, 3, 5, 7, 10, 7, 5, 3};
    static constexpr std::size_t kArpeggioLength = sizeof(kArpeggioSemitones) / sizeof(kArpeggioSemitones[0]);

    static constexpr float kVelocityPattern[] = {1.0f, 0.72f, 0.88f, 0.6f, 0.94f, 0.8f};
    static constexpr std::size_t kVelocityPatternLength = sizeof(kVelocityPattern) / sizeof(kVelocityPattern[0]);

    // Standard 8-string guitar tuning, low to high (F#1 B1 E2 A2 D3 G3 B3 E4); the top six entries
    // are the standard 6-string tuning tests/dsp/DenormalTests.cpp's kChordNotes already uses.
    static constexpr int kOpenStringMidiNote[kMaxStrings] = {30, 35, 40, 45, 50, 55, 59, 64};

    int openStringNote(int stringIdx) const noexcept {
        const int baseIndex = kMaxStrings - numStrings_; // use the top numStrings_ strings
        return kOpenStringMidiNote[static_cast<std::size_t>(baseIndex + stringIdx)];
    }

    NoteEvent makeNoteEvent(int stringIdx) noexcept {
        const auto idx = static_cast<std::size_t>(stringIdx);

        NoteEvent event{};
        event.type = NoteEventType::NoteOn;
        event.sampleOffset = 0; // overwritten by fillBlock() once the block-relative offset is known
        event.stringIndex = static_cast<std::uint8_t>(stringIdx);
        event.channel = 0;

        const int rawNote = openStringNote(stringIdx) + kArpeggioSemitones[noteCycleIndex_[idx] % kArpeggioLength];
        event.midiNote = static_cast<std::uint8_t>(std::clamp(rawNote, kMinMidiNote, kMaxMidiNote));
        event.velocity = kVelocityPattern[(noteCycleIndex_[idx] + idx) % kVelocityPatternLength];
        // kUnspecifiedNoteParam: exactly what NoteAllocator emits for a plain MIDI note-on
        // (NoteAllocator.h), so the exciter resolves position/hardness against its own defaults --
        // i.e. cnpg_bench's events are shaped the way the real plugin's events are shaped.
        event.pluckPosition = kUnspecifiedNoteParam;
        event.hardness = kUnspecifiedNoteParam;

        ++noteCycleIndex_[idx];
        return event;
    }

    int numStrings_;
    long long intervalSamples_ = 1;
    std::array<long long, kMaxStrings> nextRetriggerSample_{};
    std::array<std::size_t, kMaxStrings> noteCycleIndex_{};
    std::vector<DueEvent> due_; // fillBlock() scratch; grows once, reused every call
};

// -------------------------------------------------------------------------------------------
// CLI
// -------------------------------------------------------------------------------------------

struct BenchArgs {
    int strings = 1;
    double sampleRate = 48000.0;
    int blockSize = 128;
    int oversample = Oversampler::kDefaultFactor;
    double seconds = 60.0;
    std::string configName;
};

void printUsage(std::FILE* stream) {
    std::fprintf(stream,
                 "usage: cnpg_bench [--config <name> | --strings N] --samplerate R --blocksize B "
                 "--oversample F --seconds S\n"
                 "  --config <name>  named bench configuration (none exist yet; land in Task P2.1)\n"
                 "  --strings N      active string count, 1..%d (default 1)\n"
                 "  --samplerate R   sample rate in Hz (default 48000)\n"
                 "  --blocksize B    block size in samples (default 128)\n"
                 "  --oversample F   oversampling factor, snapped to {2,4,8} (default %d)\n"
                 "  --seconds S      render length in seconds (default 60)\n",
                 kMaxStrings, Oversampler::kDefaultFactor);
}

bool parseDouble(const char* text, double& out) noexcept {
    char* end = nullptr;
    errno = 0;
    const double value = std::strtod(text, &end);
    if (end == text || *end != '\0' || errno == ERANGE || !std::isfinite(value))
        return false;
    out = value;
    return true;
}

bool parseInt(const char* text, int& out) noexcept {
    char* end = nullptr;
    errno = 0;
    const long value = std::strtol(text, &end, 10);
    if (end == text || *end != '\0' || errno == ERANGE || value < std::numeric_limits<int>::min() ||
        value > std::numeric_limits<int>::max())
        return false;
    out = static_cast<int>(value);
    return true;
}

// Named --config resolution. No entries exist through P1 (docs/plan.md line 1146: "named configs
// arrive in P2"); Task P2.1 is the only place that ever needs to touch this function -- add
// p2_default6/p2_max8 to the table it walks -- the CLI parser, validation and error text above
// and below never change.
struct NamedConfig {
    const char* name;
    int strings;
};
constexpr NamedConfig kNamedConfigs[1] = {{"", 0}}; // placeholder-free empty table: see the note below

bool resolveNamedConfig(const std::string& name, int& outStrings) noexcept {
    // kNamedConfigs cannot be a genuinely zero-length array (ill-formed in standard C++), so it
    // holds one sentinel entry with an empty name -- which can never match a real --config value,
    // since argv strings are never empty -- and this loop is what P2.1 extends with real rows.
    for (const NamedConfig& config : kNamedConfigs) {
        if (config.name[0] != '\0' && name == config.name) {
            outStrings = config.strings;
            return true;
        }
    }
    return false;
}

bool parseArgs(int argc, char** argv, BenchArgs& args, bool& configGiven, bool& stringsGiven) {
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];

        const auto nextValue = [&](const char* flagName) -> const char* {
            if (i + 1 >= argc) {
                std::fprintf(stderr, "cnpg_bench: missing value for %s\n", flagName);
                return nullptr;
            }
            return argv[++i];
        };

        if (arg == "--config") {
            const char* value = nextValue("--config");
            if (value == nullptr)
                return false;
            args.configName = value;
            configGiven = true;
        } else if (arg == "--strings") {
            const char* value = nextValue("--strings");
            if (value == nullptr || !parseInt(value, args.strings)) {
                std::fprintf(stderr, "cnpg_bench: invalid --strings value\n");
                return false;
            }
            stringsGiven = true;
        } else if (arg == "--samplerate") {
            const char* value = nextValue("--samplerate");
            if (value == nullptr || !parseDouble(value, args.sampleRate)) {
                std::fprintf(stderr, "cnpg_bench: invalid --samplerate value\n");
                return false;
            }
        } else if (arg == "--blocksize") {
            const char* value = nextValue("--blocksize");
            if (value == nullptr || !parseInt(value, args.blockSize)) {
                std::fprintf(stderr, "cnpg_bench: invalid --blocksize value\n");
                return false;
            }
        } else if (arg == "--oversample") {
            const char* value = nextValue("--oversample");
            if (value == nullptr || !parseInt(value, args.oversample)) {
                std::fprintf(stderr, "cnpg_bench: invalid --oversample value\n");
                return false;
            }
        } else if (arg == "--seconds") {
            const char* value = nextValue("--seconds");
            if (value == nullptr || !parseDouble(value, args.seconds)) {
                std::fprintf(stderr, "cnpg_bench: invalid --seconds value\n");
                return false;
            }
        } else if (arg == "--help" || arg == "-h") {
            printUsage(stdout);
            std::exit(0);
        } else {
            std::fprintf(stderr, "cnpg_bench: unknown argument '%s'\n", arg.c_str());
            return false;
        }
    }
    return true;
}

// -------------------------------------------------------------------------------------------
// Stats
// -------------------------------------------------------------------------------------------

// Nearest-rank percentile over an already-sorted (ascending) vector. Not linear-interpolated:
// docs/plan.md section 4.7 only ever asks for "median, p99, and max", and the P1.8 ledger note
// (single-run figures get ~2 significant figures on a shared workstation) makes interpolation
// precision here moot -- nearest-rank also matches the simpler median() helper
// tests/dsp/DenormalTests.cpp already established for this repo's block-timing reports.
double percentileOfSorted(const std::vector<double>& sorted, double p) noexcept {
    if (sorted.empty())
        return 0.0;
    const auto rank = static_cast<std::size_t>(p * static_cast<double>(sorted.size() - 1) + 0.5);
    return sorted[std::min(rank, sorted.size() - 1)];
}

const char* compilerName() noexcept {
#if defined(_MSC_VER)
    return "MSVC " CNPG_BENCH_STRINGIZE(_MSC_VER);
#elif defined(__clang__)
    return "Clang " __clang_version__;
#elif defined(__GNUC__)
    return "GCC " CNPG_BENCH_STRINGIZE(__GNUC__) "." CNPG_BENCH_STRINGIZE(__GNUC_MINOR__);
#else
    return "unknown";
#endif
}

} // namespace

int main(int argc, char** argv) {
    BenchArgs args;
    bool configGiven = false;
    bool stringsGiven = false;

    if (!parseArgs(argc, argv, args, configGiven, stringsGiven)) {
        printUsage(stderr);
        return 1;
    }

    if (configGiven && stringsGiven) {
        std::fprintf(stderr, "cnpg_bench: specify either --config or --strings, not both\n");
        return 1;
    }

    if (configGiven) {
        int resolvedStrings = 0;
        if (!resolveNamedConfig(args.configName, resolvedStrings)) {
            std::fprintf(stderr,
                         "cnpg_bench: unknown --config '%s' -- no named configs exist yet (they "
                         "land in Task P2.1); use --strings N instead\n",
                         args.configName.c_str());
            return 1;
        }
        args.strings = resolvedStrings;
    }

    if (args.strings < 1 || args.strings > kMaxStrings) {
        std::fprintf(stderr, "cnpg_bench: --strings must be within 1..%d\n", kMaxStrings);
        return 1;
    }
    if (!(args.sampleRate > 0.0) || args.sampleRate > 500000.0) {
        std::fprintf(stderr, "cnpg_bench: --samplerate must be a positive, finite value\n");
        return 1;
    }
    if (args.blockSize < 1 || args.blockSize > 1000000) {
        std::fprintf(stderr, "cnpg_bench: --blocksize must be within 1..1000000\n");
        return 1;
    }
    if (args.oversample < 1 || args.oversample > kMaxOversampling) {
        std::fprintf(stderr, "cnpg_bench: --oversample must be within 1..%d (snapped to {2,4,8})\n", kMaxOversampling);
        return 1;
    }
    if (!(args.seconds > 0.0) || args.seconds > 100000.0) {
        std::fprintf(stderr, "cnpg_bench: --seconds must be a positive, finite value\n");
        return 1;
    }

    BenchChain chain;
    chain.prepare(args.sampleRate, args.blockSize, args.strings, args.oversample);
    chain.setDefaults();
    chain.reset();

    NoteStreamGenerator generator(args.strings, args.sampleRate);

    const auto totalSamples = static_cast<long long>(args.seconds * args.sampleRate);
    constexpr double kWarmupSeconds = 1.0;
    const auto warmupSamplesRaw = static_cast<long long>(kWarmupSeconds * args.sampleRate);
    const long long warmupSamples = std::min(warmupSamplesRaw, totalSamples / 2);

    BlockEventQueue events;
    std::vector<double> blockMicros; // every measured block, in render order
    blockMicros.reserve(static_cast<std::size_t>(totalSamples / std::max(args.blockSize, 1) + 1));

    long long rendered = 0;
    long long nonFiniteSamples = 0;
    int warmupBlocks = 0;

    // FNV-1a over every rendered sample's raw bit pattern (untimed -- computed after `elapsed` is
    // captured, so it never pollutes a block-time measurement). This is the empirical determinism
    // check docs/plan.md section 4.7's "seeded/fixed... so runs are comparable" is asking for:
    // two runs with identical CLI arguments must print an identical audioHash, which is a much
    // stronger claim than "the note stream and the DSP chain contain no RNG or wall-clock read, so
    // it should be deterministic by construction" -- this is what actually checks that construction
    // held, on the real compiled binary, every time it runs.
    std::uint64_t audioHash = 14695981039346656037ull; // FNV-1a 64-bit offset basis
    constexpr std::uint64_t kFnvPrime = 1099511628211ull;

    while (rendered < totalSamples) {
        const auto numSamples = static_cast<int>(std::min<long long>(args.blockSize, totalSamples - rendered));

        events.clear();
        generator.fillBlock(rendered, numSamples, events);

        const auto start = std::chrono::steady_clock::now();
        {
            const ScopedFtzDazGuard ftzDazGuard; // exactly the guard the plugin's processBlock() engages
            chain.processBlock(events, numSamples);
        }
        const auto elapsed = std::chrono::steady_clock::now() - start;
        const double micros =
            static_cast<double>(std::chrono::duration_cast<std::chrono::nanoseconds>(elapsed).count()) / 1000.0;

        blockMicros.push_back(micros);
        if (rendered < warmupSamples)
            ++warmupBlocks;

        for (int n = 0; n < numSamples; ++n) {
            const Sample sample = chain.mono[static_cast<std::size_t>(n)];
            nonFiniteSamples += std::isfinite(sample) ? 0 : 1;

            std::uint32_t bits = 0;
            std::memcpy(&bits, &sample, sizeof(bits));
            audioHash ^= bits;
            audioHash *= kFnvPrime;
        }

        rendered += numSamples;
    }

    // Clamp the warmup cut so at least one measured block always survives, even for a --seconds
    // value too short for a full kWarmupSeconds window (an edge case only a deliberately tiny
    // --seconds for smoke-testing the CLI would hit).
    const auto warmupCount = static_cast<std::size_t>(std::min(
        warmupBlocks, static_cast<int>(blockMicros.size()) - 1 < 0 ? 0 : static_cast<int>(blockMicros.size()) - 1));

    std::vector<double> stable(blockMicros.begin() + static_cast<std::vector<double>::difference_type>(warmupCount),
                               blockMicros.end());
    std::sort(stable.begin(), stable.end());

    const double medianMicros = percentileOfSorted(stable, 0.50);
    const double p99Micros = percentileOfSorted(stable, 0.99);
    const double maxMicros = stable.empty() ? 0.0 : stable.back();

    const double blockPeriodMicros = 1000000.0 * static_cast<double>(args.blockSize) / args.sampleRate;
    const auto toCpuPercent = [&](double micros) { return 100.0 * micros / blockPeriodMicros; };

    const int factor = chain.oversampler.factor();

    std::printf("cnpg_bench -- P1 monitoring chain, deterministic corpus-derived workload\n");
    std::printf("  strings=%d samplerate=%.0f blocksize=%d oversample=%d(requested %d) seconds=%.1f\n", args.strings,
                args.sampleRate, args.blockSize, factor, args.oversample, args.seconds);
    std::printf("  blocks total=%d measured=%d (warmup excluded=%d) nonFiniteSamples=%lld\n",
                static_cast<int>(blockMicros.size()), static_cast<int>(stable.size()), static_cast<int>(warmupCount),
                nonFiniteSamples);
    std::printf("  audioHash (FNV-1a/64 over every rendered sample; identical CLI args -> identical hash): "
                "%016llx\n",
                static_cast<unsigned long long>(audioHash));
    std::printf("  block period at this rate/blocksize: %.4f us (100%% of one core)\n", blockPeriodMicros);
    std::printf("  median block time: %10.3f us = %6.3f%% CPU\n", medianMicros, toCpuPercent(medianMicros));
    std::printf("  p99    block time: %10.3f us = %6.3f%% CPU\n", p99Micros, toCpuPercent(p99Micros));
    std::printf("  max    block time: %10.3f us = %6.3f%% CPU\n", maxMicros, toCpuPercent(maxMicros));

    std::printf("{\"strings\":%d,\"sampleRate\":%.0f,\"blockSize\":%d,\"oversampleFactor\":%d,"
                "\"secondsRequested\":%.1f,\"blocksTotal\":%d,\"blocksMeasured\":%d,\"warmupBlocksExcluded\":%d,"
                "\"nonFiniteSamples\":%lld,\"audioHash\":\"%016llx\",\"medianBlockTimeUs\":%.3f,"
                "\"p99BlockTimeUs\":%.3f,\"maxBlockTimeUs\":%.3f,\"medianCpuPercent\":%.3f,\"p99CpuPercent\":%.3f,"
                "\"maxCpuPercent\":%.3f,\"compiler\":\"%s\",\"ndebug\":%s,\"gitCommit\":\"%s\"}\n",
                args.strings, args.sampleRate, args.blockSize, factor, args.seconds,
                static_cast<int>(blockMicros.size()), static_cast<int>(stable.size()), static_cast<int>(warmupCount),
                nonFiniteSamples, static_cast<unsigned long long>(audioHash), medianMicros, p99Micros, maxMicros,
                toCpuPercent(medianMicros), toCpuPercent(p99Micros), toCpuPercent(maxMicros), compilerName(),
#if defined(NDEBUG)
                "true",
#else
                "false",
#endif
                CNPG_BENCH_GIT_COMMIT);

    return 0;
}
